"""
Module to keep all the constants commonly used by other modules.

Can be imported from anywhere.
"""
FRAME_RATE = 60

STR_GAME_TITLE = 'Python - Snake'

MAIN_WIN_SIZE = 952
WIN_WIDTH_TILES = 28

TILE_SIZE = MAIN_WIN_SIZE // WIN_WIDTH_TILES

MAP_MARGIN_TILES = 3
MAP_MARGIN = MAP_MARGIN_TILES * TILE_SIZE

BORDER_WIDTH_TILES = 0.5
BORDER_WIDTH = BORDER_WIDTH_TILES * TILE_SIZE

MAP_SIZE_TILES = WIN_WIDTH_TILES - MAP_MARGIN_TILES - MAP_MARGIN_TILES
MAP_SIZE = MAP_SIZE_TILES * TILE_SIZE

SNAKE_SPEED = 80

BACKGROUND_COLOR = (97, 79, 75)
BORDER_COLOR = (77, 161, 196)
TILES_COLOR = (46, 51, 54)
SECOND_TILES_COLOR = (63, 69, 73)
SNAKE_COLOR = (133, 196, 77)
HEAD_COLOR = (196, 141, 77)
APPLE_COLOR = (171, 67, 67)
