"""
Module to keep all the constants commonly used by other modules.

Can be imported from anywhere.
"""
FRAME_RATE = 60

STR_GAME_TITLE = 'Python - Snake'

MAIN_WIN_WIDTH = 950
MAIN_WIN_HEIGHT = 950

MAP_MARGIN = 80

MAX_MAP_WIDTH = MAIN_WIN_HEIGHT - MAP_MARGIN - MAP_MARGIN
MAX_MAP_HEIGHT = MAIN_WIN_HEIGHT - MAP_MARGIN - MAP_MARGIN

TILE_SIZE = 36

GRID_WIDTH = (MAIN_WIN_WIDTH - MAP_MARGIN) / TILE_SIZE
GRID_HEIGHT = (MAIN_WIN_HEIGHT - MAP_MARGIN) / TILE_SIZE

BORDER_WIDTH = 15

BACKGROUND_COLOR = (97, 79, 75)
BORDER_COLOR = (77, 161, 196)
TILES_COLOR = (46, 51, 54)
SECOND_TILES_COLOR = (63, 69, 73)
SNAKE_COLOR = (133, 196, 77)
HEAD_COLOR = (196, 141, 77)
APPLE_COLOR = (171, 67, 67)

SNAKE_SPEED = 80
